spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tcmaster}
    username: ${SPRING_DATASOURCE_USERNAME:tcmaster}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: ${JWT_SECRET}
  expiration-minutes: 60

springdoc:
  swagger-ui:
    path: /swagger-ui.html
